export const  GET_LATEST_EVENTS = "GET_LATEST_EVENTS";

export const  GET_FILTERED_EVENTS = "GET_FILTERED_EVENTS";

export const  GET_EVENT_DATA = "GET_EVENT_DATA";

export const  GET_PARTICIPANTS = "GET_PARTICIPANTS";

export const  GET_USER_EVENTS_SUCCESS = "GET_USER_EVENTS";

export const  ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";