export const  CHANGE_MODAL_VISIBLE  = "CHANGE_MODAL_VISIBLE";

export const  LOGIN_USER_SUCCESS    = "LOGIN_USER_SUCCESS",
              LOGIN_USER_FAILURE    = "LOGIN_USER_FAILURE";

export const  LOGOUT_USER_SUCCESS   = "LOGOUT_USER_SUCCESS",
              LOGOUT_USER_FAILURE   = "LOGOUT_USER_SUCCESS";

export const  REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
              REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const  GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS",
              GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const  GET_USER_EVENTS_SUCCESS = "GET_USER_EVENTS";

export const  GET_COMMENTS_SUCCESS = "GET_COMMENTS";